# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        #python-version: [3.7, 3.8, 3.9]
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get install libgirepository1.0-dev gcc libcairo2-dev pkg-config python3-dev gir1.2-gtk-3.0 --yes
        python -m pip install --upgrade pip
        python -m pip install wheel
        pip install python3-all
        python -m pip install flake8 pytest         
        python -m pip install stdeb debhelper 
        python -m pip install PyGObject
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        ## flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --builtins="_,xrange"   ==> this causes too many F821 (undefined) errors.
        # flake8 . --count --builtins="_,xrange" --select=E9,F63,F7 --show-source --statistics  
        ## exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        #flake8 . --count --builtins="_,xrange" --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    #- name: Test with pytest
    #  run: |
    #    pytest pdfbooklet.pdfbooklet3.py
    - name: Create package
      run: |
        python build.py
        make-deb 
        ls -lR ./ > lsdebian.txt
        python setup.py --command-packages=stdeb.command bdist_deb
        
    - name: builds 1
      uses: actions/upload-artifact@v2
      with:
        name: builds1
        path: dist
     
    - name: deb 
      uses: actions/upload-artifact@v2      
      with:
        name: deb 
        path: deb_dist